# Generated by Django 4.0.3 on 2022-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('part_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=2000)),
                ('images', models.ImageField(upload_to='document')),
                ('pdf', models.FileField(upload_to='document')),
            ],
        ),
    ]
