# Generated by Django 3.2.7 on 2022-04-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolsons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientsM',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='clients/logos')),
                ('companyName', models.CharField(max_length=200)),
            ],
        ),
    ]
