# Generated by Django 3.2.7 on 2022-04-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolsons', '0002_clientsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
