# Generated by Django 3.2.7 on 2022-04-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kolsons', '0003_alter_clientsm_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificatsM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificateimage', models.ImageField(upload_to='certificats/image')),
                ('certificatePDF', models.FileField(upload_to='certificats/pdf')),
                ('certificateInfo', models.CharField(max_length=300)),
            ],
        ),
    ]
