# Generated by Django 3.2.7 on 2022-04-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kolsons', '0002_remove_product_pdf_product_colour_of_light_and_more'),
        ('kolsons', '0004_certificatsm'),
    ]

    operations = [
    ]
